In [18]:
from tensorflow.keras.preprocessing.text import one_hot

In [19]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [20]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [21]:
## Define the vocabulary size
voc_size=10000

In [22]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [23]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[150, 6177, 7002, 7801],
 [150, 6177, 7002, 7651],
 [150, 5733, 7002, 8014],
 [8919, 308, 9131, 6434, 881],
 [8919, 308, 9131, 6434, 1509],
 [4298, 150, 972, 7002, 5506],
 [1033, 5488, 533, 6434]]

In [24]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [25]:
import numpy as np

In [26]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0  150 6177 7002 7801]
 [   0    0    0    0  150 6177 7002 7651]
 [   0    0    0    0  150 5733 7002 8014]
 [   0    0    0 8919  308 9131 6434  881]
 [   0    0    0 8919  308 9131 6434 1509]
 [   0    0    0 4298  150  972 7002 5506]
 [   0    0    0    0 1033 5488  533 6434]]


In [27]:
## feature representation
dim=10

In [28]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [29]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [30]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 208ms/step


array([[[-0.0485638 ,  0.00574113, -0.00546587, -0.02387321,
          0.01833345, -0.02823771,  0.04355469,  0.03609357,
         -0.01258389, -0.03984597],
        [-0.0485638 ,  0.00574113, -0.00546587, -0.02387321,
          0.01833345, -0.02823771,  0.04355469,  0.03609357,
         -0.01258389, -0.03984597],
        [-0.0485638 ,  0.00574113, -0.00546587, -0.02387321,
          0.01833345, -0.02823771,  0.04355469,  0.03609357,
         -0.01258389, -0.03984597],
        [-0.0485638 ,  0.00574113, -0.00546587, -0.02387321,
          0.01833345, -0.02823771,  0.04355469,  0.03609357,
         -0.01258389, -0.03984597],
        [ 0.01626321,  0.04791282,  0.04183665,  0.03850252,
          0.02135466,  0.00474236,  0.00082837, -0.00325124,
         -0.03928993, -0.02165967],
        [ 0.04806764, -0.01891084,  0.02195011,  0.02196569,
         -0.01510519,  0.00224072, -0.02210279,  0.04178437,
          0.04399843, -0.03717   ],
        [ 0.04119152,  0.03448978, -0.01973861, -0.0

In [31]:
embedded_docs[0]

array([   0,    0,    0,    0,  150, 6177, 7002, 7801])

In [33]:
input_data = np.expand_dims(embedded_docs[0], axis=0)
prediction = model.predict(input_data)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 140ms/step
